services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: phoenix_book_review_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_PORT=${PHX_PORT}
      - MIX_ENV=${MIX_ENV:-dev}
      - REDIS_ENABLED=false
      - ELASTICSEARCH_ENABLED=false
      - STATIC_ASSETS_SERVED_BY_PROXY=true
      - UPLOAD_PATH=/app/priv/static/uploads
    volumes:
      - .:/app
      - uploads_data:/app/priv/static/uploads
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix run priv/repo/seeds.exs &&
        mix phx.server
      "

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - uploads_data:/uploads
      - .:/app:ro
    depends_on:
      - web

volumes:
  postgres_data:
  uploads_data: