services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: phoenix_book_review_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    ports:
      - "${PHX_PORT}:${PHX_PORT}"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_PORT=${PHX_PORT}
      - MIX_ENV=${MIX_ENV:-dev}
      - REDIS_ENABLED=false
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - STATIC_ASSETS_SERVED_BY_PROXY=false
      - UPLOAD_PATH=${UPLOAD_PATH}
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database and Elasticsearch...' &&
        sleep 15 &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix run priv/repo/seeds.exs &&
        mix phx.server
      "

volumes:
  postgres_data:
  elasticsearch_data: